### PR TITLE
adding dplyr hw assignment markdown file only

### PR DESCRIPTION
**Pull request by vpnagraj**

### CODE REVIEW

**Comment by stephenturner** [comment]
thanks. can you actually commit the .Rmd file, not just the .md?

**Comment by vpnagraj** [comment]
sure thing – but will that make the answers visible to students? i guess i can commit and we can just link to md?

**Comment by vpnagraj** [comment]
cool html and rmd are added

**Comment by stephenturner** [comment]
thanks, will review. 

re: 

> but will that make the answers visible to students?

We can remove the Rmd from the repo later on without removing it locally. E.g.

http://stackoverflow.com/a/1143800/654296

**Comment by stephenturner** [comment]
thanks, @vpnagraj  you probably want to run a `git pull` - I made a few minor changes before merging.

**Pull request merged**
